[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirect for confirmation page to ensure it works with Supabase
[[redirects]]
  from = "/confirm"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/confirm/*"
  to = "/index.html"
  status = 200